name:                spago
version:             0.6.0.0
github:              "spacchetti/spago"
license:             BSD3
author:              "Justin Woo, Fabrizio Ferrai"
maintainer:          "@jusrin00, @fabferrai"
copyright:           "2018 Justin Woo, Fabrizio Ferrai"

extra-source-files:
- README.md
- ChangeLog.md

ghc-options:
  - -Wall

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/spacchetti/spago#readme>

default-extensions:
- DeriveDataTypeable
- DeriveGeneric
- DerivingStrategies
- DuplicateRecordFields
- GeneralizedNewtypeDeriving
- LambdaCase
- RecordWildCards
- ScopedTypeVariables
- OverloadedStrings

dependencies:
- base >= 4.7 && < 5
- text < 1.3
- turtle
- filepath
- file-embed
- aeson
- aeson-pretty
- containers
- dhall
- dhall-json
- bytestring
- prettyprinter
- async-pool
- process
- template-haskell

executables:
  spago:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
