resolver: lts-21.11
packages:
  - .
extra-deps:
  - semver-range-0.2.8
  - async-pool-0.9.2
  - bower-json-1.1.0.0
  - aeson-better-errors-0.9.1.1
allow-newer: true
nix:
  packages: [zlib]
flags:
  aeson-pretty:
    lib-only: true
  # This is so we don't depend on libtinfo
  # haskeline:
  #   terminfo: false
  #   examples: false
  cryptonite:
    use_target_attributes: false
