resolver: lts-18.24
packages:
  - .
extra-deps:
  - semver-range-0.2.8
  - with-utf8-1.0.2.2
allow-newer: true
nix:
  packages: [zlib]
flags:
  aeson-pretty:
    lib-only: true
  # This is so we don't depend on libtinfo
  haskeline:
    terminfo: false
    examples: false
  cryptonite:
    use_target_attributes: false
