{ name = "optparse"
, dependencies =
  [ "prelude"
  , "effect"
  , "exitcodes"
  , "strings"
  , "arrays"
  , "console"
  , "open-memoize"
  , "transformers"
  , "exists"
  , "node-process"
  , "free"
  , "quickcheck"
  , "spec"
  , "aff"
  , "bifunctors"
  , "control"
  , "either"
  , "enums"
  , "foldable-traversable"
  , "gen"
  , "integers"
  , "lazy"
  , "lists"
  , "maybe"
  , "newtype"
  , "node-buffer"
  , "node-streams"
  , "nonempty"
  , "numbers"
  , "partial"
  , "tailrec"
  , "tuples"
  ]
, packages = ./packages.dhall
, sources = [ "src/**/*.purs", "test/**/*.purs" ]
, license = "BSD-3-Clause"
, repository = "https://github.com/f-o-a-m/purescript-optparse"
}
