{ name = "language-cst-parser"
, license = "MIT"
, repository = "https://github.com/natefaubion/purescript-language-cst-parser.git"
, dependencies =
  [ "arrays"
  , "console"
  , "const"
  , "control"
  , "effect"
  , "either"
  , "enums"
  , "foldable-traversable"
  , "free"
  , "functions"
  , "functors"
  , "identity"
  , "integers"
  , "lazy"
  , "lists"
  , "maybe"
  , "newtype"
  , "node-process"
  , "numbers"
  , "ordered-collections"
  , "partial"
  , "prelude"
  , "st"
  , "strings"
  , "transformers"
  , "tuples"
  , "typelevel-prelude"
  , "unfoldable"
  , "unsafe-coerce"
  ]
, packages = ./packages.dhall
, sources = [ "src/**/*.purs", "test/**/Main.purs" ]
}
