{ name = "dodo-printer"
, license = "MIT"
, repository = "https://github.com/natefaubion/purescript-dodo-printer.git"
, dependencies =
  [ "aff"
  , "ansi"
  , "arrays"
  , "avar"
  , "console"
  , "control"
  , "effect"
  , "either"
  , "exceptions"
  , "foldable-traversable"
  , "integers"
  , "lists"
  , "maybe"
  , "minibench"
  , "newtype"
  , "node-buffer"
  , "node-child-process"
  , "node-fs-aff"
  , "node-path"
  , "node-process"
  , "node-streams"
  , "parallel"
  , "partial"
  , "posix-types"
  , "prelude"
  , "safe-coerce"
  , "strings"
  , "tuples"
  ]
, packages = ./packages.dhall
, sources = [ "src/**/*.purs", "test/**/*.purs" ]
}
