package:
  name: aaaa
  dependencies:
    - console
    - effect
    - prelude
  test:
    main: Test.Main
    dependencies: []
workspace:
  package_set:
    path: ../local-package-set.json
  extra_packages: {}
