{ name = "node-execa"
, dependencies =
  [ "aff"
  , "arrays"
  , "control"
  , "effect"
  , "either"
  , "exceptions"
  , "foldable-traversable"
  , "foreign"
  , "foreign-object"
  , "functions"
  , "integers"
  , "js-timers"
  , "maybe"
  , "node-buffer"
  , "node-event-emitter"
  , "node-fs"
  , "node-human-signals"
  , "node-path"
  , "node-process"
  , "node-streams"
  , "nullable"
  , "numbers"
  , "ordered-collections"
  , "parallel"
  , "parsing"
  , "partial"
  , "posix-types"
  , "prelude"
  , "profunctor-lenses"
  , "record"
  , "refs"
  , "safe-coerce"
  , "strings"
  , "tailrec"
  , "transformers"
  , "tuples"
  , "unsafe-coerce"
  , "unsafe-reference"
  ]
, packages = ./packages.dhall
, sources = [ "src/**/*.purs" ]
}
