#!/usr/bin/env bash
set -e

TAG=PACKAGE_VERSION

# exit if there is evidence of installation
[ -e ./spago.tar.gz ] && exit 0;

# remove stubs
rm ./spago

# osx or linux install
if [ "$(uname -s)" == "Darwin" ]
then
  curl --location --output ./spago.tar.gz --silent https://github.com/spacchetti/spago/releases/download/$TAG/osx.tar.gz
else
  wget -O ./spago.tar.gz https://github.com/spacchetti/spago/releases/download/$TAG/linux.tar.gz
fi

# unpack
tar -xvf ./spago.tar.gz -C ./
