#!/usr/bin/env node
const cp = require("child_process");

const spago = cp.spawn(__dirname + '/spago.exe', process.argv.slice(2), {stdio: 'inherit'});
spago.on('error', (err) => {
    console.log("Downloading the spago binary failed. Please try reinstalling the spago npm package.");
});
