#!/usr/bin/env node
// This file is only used on Windows. In *nix NPM installations it's replaced
// with the actual spago binary.

const cp = require("child_process");

// Ignore SIGINT (Ctrl-C) because we don't want to terminate this process from
// it (#483). Spago.exe will handle it for us
process.on('SIGINT', () => {});

const spago = cp.spawn(__dirname + '/spago.exe', process.argv.slice(2), {stdio: 'inherit'});
spago.on('error', (err) => {
    console.log("Downloading the spago binary failed. Please try reinstalling the spago npm package.");
});
spago.on('exit', (code) => {
    process.exit(code);
});
